# Generated by Django 3.1.7 on 2021-03-18 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0002_reading_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sensors.plant'),
        ),
    ]
