# Generated by Django 3.1.7 on 2021-03-18 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0003_auto_20210318_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='location',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sensors.plant'),
        ),
    ]
